import { Chapter } from '../types';

export const INITIAL_CHAPTERS: Chapter[] = [
  // --- PHYSICS CLASS 11 ---
  {
    id: 'phy-11-1',
    subject: 'physics',
    name: 'Units, Dimensions & Errors',
    classLevel: '11',
    theory: 'completed',
    questionsSolved: 45,
    questionsTarget: 60,
    pyqsStatus: 'completed',
    revisionCount: 2,
    formulaSheet: true,
  },
  {
    id: 'phy-11-2',
    subject: 'physics',
    name: 'Kinematics (1D & 2D Motion, Projectile)',
    classLevel: '11',
    theory: 'completed',
    questionsSolved: 80,
    questionsTarget: 100,
    pyqsStatus: 'mastered',
    revisionCount: 2,
    formulaSheet: true,
  },
  {
    id: 'phy-11-3',
    subject: 'physics',
    name: 'Newton\'s Laws of Motion & Friction',
    classLevel: '11',
    theory: 'completed',
    questionsSolved: 95,
    questionsTarget: 100,
    pyqsStatus: 'completed',
    revisionCount: 1,
    formulaSheet: true,
  },
  {
    id: 'phy-11-4',
    subject: 'physics',
    name: 'Work, Power & Energy',
    classLevel: '11',
    theory: 'completed',
    questionsSolved: 70,
    questionsTarget: 90,
    pyqsStatus: 'partial',
    revisionCount: 1,
    formulaSheet: true,
  },
  {
    id: 'phy-11-5',
    subject: 'physics',
    name: 'Center of Mass & Collisions',
    classLevel: '11',
    theory: 'in_progress',
    questionsSolved: 40,
    questionsTarget: 80,
    pyqsStatus: 'partial',
    revisionCount: 1,
    formulaSheet: false,
  },
  {
    id: 'phy-11-6',
    subject: 'physics',
    name: 'Rotational Motion & Rigid Body Dynamics',
    classLevel: '11',
    theory: 'in_progress',
    questionsSolved: 55,
    questionsTarget: 120,
    pyqsStatus: 'partial',
    revisionCount: 0,
    formulaSheet: false,
  },
  {
    id: 'phy-11-7',
    subject: 'physics',
    name: 'Gravitation',
    classLevel: '11',
    theory: 'completed',
    questionsSolved: 50,
    questionsTarget: 60,
    pyqsStatus: 'completed',
    revisionCount: 1,
    formulaSheet: true,
  },
  {
    id: 'phy-11-8',
    subject: 'physics',
    name: 'Fluid Mechanics & Surface Tension',
    classLevel: '11',
    theory: 'not_started',
    questionsSolved: 0,
    questionsTarget: 70,
    pyqsStatus: 'none',
    revisionCount: 0,
    formulaSheet: false,
  },
  {
    id: 'phy-11-9',
    subject: 'physics',
    name: 'Thermodynamics & Kinetic Theory of Gases',
    classLevel: '11',
    theory: 'completed',
    questionsSolved: 65,
    questionsTarget: 80,
    pyqsStatus: 'completed',
    revisionCount: 2,
    formulaSheet: true,
  },
  {
    id: 'phy-11-10',
    subject: 'physics',
    name: 'Simple Harmonic Motion (SHM)',
    classLevel: '11',
    theory: 'in_progress',
    questionsSolved: 35,
    questionsTarget: 70,
    pyqsStatus: 'partial',
    revisionCount: 0,
    formulaSheet: false,
  },
  {
    id: 'phy-11-11',
    subject: 'physics',
    name: 'Waves & Sound (Doppler Effect)',
    classLevel: '11',
    theory: 'not_started',
    questionsSolved: 0,
    questionsTarget: 70,
    pyqsStatus: 'none',
    revisionCount: 0,
    formulaSheet: false,
  },

  // --- PHYSICS CLASS 12 ---
  {
    id: 'phy-12-1',
    subject: 'physics',
    name: 'Electrostatics & Electric Field/Potential',
    classLevel: '12',
    theory: 'completed',
    questionsSolved: 90,
    questionsTarget: 120,
    pyqsStatus: 'mastered',
    revisionCount: 2,
    formulaSheet: true,
  },
  {
    id: 'phy-12-2',
    subject: 'physics',
    name: 'Capacitance & Dielectrics',
    classLevel: '12',
    theory: 'completed',
    questionsSolved: 60,
    questionsTarget: 70,
    pyqsStatus: 'completed',
    revisionCount: 1,
    formulaSheet: true,
  },
  {
    id: 'phy-12-3',
    subject: 'physics',
    name: 'Current Electricity & Circuit Laws',
    classLevel: '12',
    theory: 'completed',
    questionsSolved: 110,
    questionsTarget: 120,
    pyqsStatus: 'mastered',
    revisionCount: 2,
    formulaSheet: true,
  },
  {
    id: 'phy-12-4',
    subject: 'physics',
    name: 'Magnetic Effects of Current & Biot-Savart',
    classLevel: '12',
    theory: 'in_progress',
    questionsSolved: 40,
    questionsTarget: 80,
    pyqsStatus: 'partial',
    revisionCount: 0,
    formulaSheet: false,
  },
  {
    id: 'phy-12-5',
    subject: 'physics',
    name: 'Electromagnetic Induction (EMI)',
    classLevel: '12',
    theory: 'not_started',
    questionsSolved: 0,
    questionsTarget: 75,
    pyqsStatus: 'none',
    revisionCount: 0,
    formulaSheet: false,
  },
  {
    id: 'phy-12-6',
    subject: 'physics',
    name: 'Alternating Current (AC)',
    classLevel: '12',
    theory: 'not_started',
    questionsSolved: 0,
    questionsTarget: 50,
    pyqsStatus: 'none',
    revisionCount: 0,
    formulaSheet: false,
  },
  {
    id: 'phy-12-7',
    subject: 'physics',
    name: 'Ray Optics & Optical Instruments',
    classLevel: '12',
    theory: 'in_progress',
    questionsSolved: 30,
    questionsTarget: 90,
    pyqsStatus: 'none',
    revisionCount: 0,
    formulaSheet: false,
  },
  {
    id: 'phy-12-8',
    subject: 'physics',
    name: 'Wave Optics (Interference & Diffraction)',
    classLevel: '12',
    theory: 'not_started',
    questionsSolved: 0,
    questionsTarget: 60,
    pyqsStatus: 'none',
    revisionCount: 0,
    formulaSheet: false,
  },
  {
    id: 'phy-12-9',
    subject: 'physics',
    name: 'Modern Physics (Dual Nature, Atoms, Nuclei)',
    classLevel: '12',
    theory: 'completed',
    questionsSolved: 85,
    questionsTarget: 100,
    pyqsStatus: 'mastered',
    revisionCount: 2,
    formulaSheet: true,
  },
  {
    id: 'phy-12-10',
    subject: 'physics',
    name: 'Semiconductors & Electronic Devices',
    classLevel: '12',
    theory: 'completed',
    questionsSolved: 50,
    questionsTarget: 50,
    pyqsStatus: 'completed',
    revisionCount: 1,
    formulaSheet: true,
  },

  // --- CHEMISTRY CLASS 11 ---
  {
    id: 'chem-11-1',
    subject: 'chemistry',
    name: 'Some Basic Concepts of Chemistry (Mole Concept)',
    classLevel: '11',
    theory: 'completed',
    questionsSolved: 75,
    questionsTarget: 80,
    pyqsStatus: 'mastered',
    revisionCount: 2,
    formulaSheet: true,
  },
  {
    id: 'chem-11-2',
    subject: 'chemistry',
    name: 'Atomic Structure & Quantum Numbers',
    classLevel: '11',
    theory: 'completed',
    questionsSolved: 60,
    questionsTarget: 70,
    pyqsStatus: 'completed',
    revisionCount: 1,
    formulaSheet: true,
  },
  {
    id: 'chem-11-3',
    subject: 'chemistry',
    name: 'Periodic Table & Periodicity',
    classLevel: '11',
    theory: 'completed',
    questionsSolved: 65,
    questionsTarget: 70,
    pyqsStatus: 'mastered',
    revisionCount: 2,
    formulaSheet: true,
  },
  {
    id: 'chem-11-4',
    subject: 'chemistry',
    name: 'Chemical Bonding & Molecular Structure',
    classLevel: '11',
    theory: 'completed',
    questionsSolved: 120,
    questionsTarget: 120,
    pyqsStatus: 'mastered',
    revisionCount: 3,
    formulaSheet: true,
  },
  {
    id: 'chem-11-5',
    subject: 'chemistry',
    name: 'Chemical Thermodynamics & Energetics',
    classLevel: '11',
    theory: 'completed',
    questionsSolved: 70,
    questionsTarget: 80,
    pyqsStatus: 'completed',
    revisionCount: 1,
    formulaSheet: true,
  },
  {
    id: 'chem-11-6',
    subject: 'chemistry',
    name: 'Equilibrium (Chemical & Ionic)',
    classLevel: '11',
    theory: 'in_progress',
    questionsSolved: 55,
    questionsTarget: 100,
    pyqsStatus: 'partial',
    revisionCount: 1,
    formulaSheet: false,
  },
  {
    id: 'chem-11-7',
    subject: 'chemistry',
    name: 'Redox Reactions',
    classLevel: '11',
    theory: 'completed',
    questionsSolved: 45,
    questionsTarget: 50,
    pyqsStatus: 'completed',
    revisionCount: 1,
    formulaSheet: true,
  },
  {
    id: 'chem-11-8',
    subject: 'chemistry',
    name: 'General Organic Chemistry (GOC & Isomerism)',
    classLevel: '11',
    theory: 'completed',
    questionsSolved: 130,
    questionsTarget: 140,
    pyqsStatus: 'mastered',
    revisionCount: 2,
    formulaSheet: true,
  },
  {
    id: 'chem-11-9',
    subject: 'chemistry',
    name: 'Hydrocarbons (Alkanes, Alkenes, Alkynes, Aromatic)',
    classLevel: '11',
    theory: 'in_progress',
    questionsSolved: 50,
    questionsTarget: 90,
    pyqsStatus: 'partial',
    revisionCount: 1,
    formulaSheet: false,
  },

  // --- CHEMISTRY CLASS 12 ---
  {
    id: 'chem-12-1',
    subject: 'chemistry',
    name: 'Solutions & Colligative Properties',
    classLevel: '12',
    theory: 'completed',
    questionsSolved: 65,
    questionsTarget: 70,
    pyqsStatus: 'completed',
    revisionCount: 1,
    formulaSheet: true,
  },
  {
    id: 'chem-12-2',
    subject: 'chemistry',
    name: 'Electrochemistry',
    classLevel: '12',
    theory: 'completed',
    questionsSolved: 75,
    questionsTarget: 80,
    pyqsStatus: 'completed',
    revisionCount: 1,
    formulaSheet: true,
  },
  {
    id: 'chem-12-3',
    subject: 'chemistry',
    name: 'Chemical Kinetics',
    classLevel: '12',
    theory: 'completed',
    questionsSolved: 60,
    questionsTarget: 60,
    pyqsStatus: 'mastered',
    revisionCount: 2,
    formulaSheet: true,
  },
  {
    id: 'chem-12-4',
    subject: 'chemistry',
    name: 'd- and f-Block Elements',
    classLevel: '12',
    theory: 'in_progress',
    questionsSolved: 30,
    questionsTarget: 60,
    pyqsStatus: 'partial',
    revisionCount: 0,
    formulaSheet: false,
  },
  {
    id: 'chem-12-5',
    subject: 'chemistry',
    name: 'Coordination Compounds',
    classLevel: '12',
    theory: 'completed',
    questionsSolved: 90,
    questionsTarget: 100,
    pyqsStatus: 'mastered',
    revisionCount: 2,
    formulaSheet: true,
  },
  {
    id: 'chem-12-6',
    subject: 'chemistry',
    name: 'Haloalkanes and Haloarenes',
    classLevel: '12',
    theory: 'in_progress',
    questionsSolved: 40,
    questionsTarget: 75,
    pyqsStatus: 'partial',
    revisionCount: 0,
    formulaSheet: false,
  },
  {
    id: 'chem-12-7',
    subject: 'chemistry',
    name: 'Alcohols, Phenols and Ethers',
    classLevel: '12',
    theory: 'not_started',
    questionsSolved: 0,
    questionsTarget: 75,
    pyqsStatus: 'none',
    revisionCount: 0,
    formulaSheet: false,
  },
  {
    id: 'chem-12-8',
    subject: 'chemistry',
    name: 'Aldehydes, Ketones and Carboxylic Acids',
    classLevel: '12',
    theory: 'not_started',
    questionsSolved: 0,
    questionsTarget: 90,
    pyqsStatus: 'none',
    revisionCount: 0,
    formulaSheet: false,
  },
  {
    id: 'chem-12-9',
    subject: 'chemistry',
    name: 'Amines & Diazonium Salts',
    classLevel: '12',
    theory: 'not_started',
    questionsSolved: 0,
    questionsTarget: 60,
    pyqsStatus: 'none',
    revisionCount: 0,
    formulaSheet: false,
  },
  {
    id: 'chem-12-10',
    subject: 'chemistry',
    name: 'Biomolecules',
    classLevel: '12',
    theory: 'completed',
    questionsSolved: 45,
    questionsTarget: 50,
    pyqsStatus: 'completed',
    revisionCount: 1,
    formulaSheet: true,
  },

  // --- MATHEMATICS CLASS 11 ---
  {
    id: 'math-11-1',
    subject: 'maths',
    name: 'Sets, Relations and Functions',
    classLevel: '11',
    theory: 'completed',
    questionsSolved: 70,
    questionsTarget: 80,
    pyqsStatus: 'completed',
    revisionCount: 2,
    formulaSheet: true,
  },
  {
    id: 'math-11-2',
    subject: 'maths',
    name: 'Trigonometric Functions & Equations',
    classLevel: '11',
    theory: 'completed',
    questionsSolved: 85,
    questionsTarget: 100,
    pyqsStatus: 'mastered',
    revisionCount: 2,
    formulaSheet: true,
  },
  {
    id: 'math-11-3',
    subject: 'maths',
    name: 'Complex Numbers & Quadratic Equations',
    classLevel: '11',
    theory: 'completed',
    questionsSolved: 90,
    questionsTarget: 100,
    pyqsStatus: 'completed',
    revisionCount: 1,
    formulaSheet: true,
  },
  {
    id: 'math-11-4',
    subject: 'maths',
    name: 'Permutations and Combinations (P&C)',
    classLevel: '11',
    theory: 'in_progress',
    questionsSolved: 50,
    questionsTarget: 90,
    pyqsStatus: 'partial',
    revisionCount: 1,
    formulaSheet: false,
  },
  {
    id: 'math-11-5',
    subject: 'maths',
    name: 'Binomial Theorem',
    classLevel: '11',
    theory: 'completed',
    questionsSolved: 60,
    questionsTarget: 70,
    pyqsStatus: 'completed',
    revisionCount: 2,
    formulaSheet: true,
  },
  {
    id: 'math-11-6',
    subject: 'maths',
    name: 'Sequences and Series (AP, GP, Special Series)',
    classLevel: '11',
    theory: 'completed',
    questionsSolved: 75,
    questionsTarget: 80,
    pyqsStatus: 'mastered',
    revisionCount: 2,
    formulaSheet: true,
  },
  {
    id: 'math-11-7',
    subject: 'maths',
    name: 'Straight Lines & Pair of Straight Lines',
    classLevel: '11',
    theory: 'completed',
    questionsSolved: 80,
    questionsTarget: 90,
    pyqsStatus: 'completed',
    revisionCount: 1,
    formulaSheet: true,
  },
  {
    id: 'math-11-8',
    subject: 'maths',
    name: 'Circles',
    classLevel: '11',
    theory: 'in_progress',
    questionsSolved: 45,
    questionsTarget: 80,
    pyqsStatus: 'partial',
    revisionCount: 1,
    formulaSheet: false,
  },
  {
    id: 'math-11-9',
    subject: 'maths',
    name: 'Conic Sections (Parabola, Ellipse, Hyperbola)',
    classLevel: '11',
    theory: 'in_progress',
    questionsSolved: 60,
    questionsTarget: 120,
    pyqsStatus: 'partial',
    revisionCount: 0,
    formulaSheet: false,
  },

  // --- MATHEMATICS CLASS 12 ---
  {
    id: 'math-12-1',
    subject: 'maths',
    name: 'Matrices and Determinants',
    classLevel: '12',
    theory: 'completed',
    questionsSolved: 90,
    questionsTarget: 90,
    pyqsStatus: 'mastered',
    revisionCount: 3,
    formulaSheet: true,
  },
  {
    id: 'math-12-2',
    subject: 'maths',
    name: 'Continuity & Differentiability',
    classLevel: '12',
    theory: 'completed',
    questionsSolved: 70,
    questionsTarget: 80,
    pyqsStatus: 'completed',
    revisionCount: 1,
    formulaSheet: true,
  },
  {
    id: 'math-12-3',
    subject: 'maths',
    name: 'Application of Derivatives (AOD)',
    classLevel: '12',
    theory: 'in_progress',
    questionsSolved: 50,
    questionsTarget: 100,
    pyqsStatus: 'partial',
    revisionCount: 0,
    formulaSheet: false,
  },
  {
    id: 'math-12-4',
    subject: 'maths',
    name: 'Indefinite & Definite Integration',
    classLevel: '12',
    theory: 'in_progress',
    questionsSolved: 65,
    questionsTarget: 130,
    pyqsStatus: 'partial',
    revisionCount: 0,
    formulaSheet: false,
  },
  {
    id: 'math-12-5',
    subject: 'maths',
    name: 'Differential Equations',
    classLevel: '12',
    theory: 'not_started',
    questionsSolved: 0,
    questionsTarget: 70,
    pyqsStatus: 'none',
    revisionCount: 0,
    formulaSheet: false,
  },
  {
    id: 'math-12-6',
    subject: 'maths',
    name: 'Vector Algebra',
    classLevel: '12',
    theory: 'completed',
    questionsSolved: 80,
    questionsTarget: 85,
    pyqsStatus: 'mastered',
    revisionCount: 2,
    formulaSheet: true,
  },
  {
    id: 'math-12-7',
    subject: 'maths',
    name: 'Three Dimensional Geometry (3D)',
    classLevel: '12',
    theory: 'completed',
    questionsSolved: 85,
    questionsTarget: 90,
    pyqsStatus: 'mastered',
    revisionCount: 2,
    formulaSheet: true,
  },
  {
    id: 'math-12-8',
    subject: 'maths',
    name: 'Probability & Bayes Theorem',
    classLevel: '12',
    theory: 'not_started',
    questionsSolved: 0,
    questionsTarget: 80,
    pyqsStatus: 'none',
    revisionCount: 0,
    formulaSheet: false,
  },
];
